package ua.turbosms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-02-21T16:50:44.696+02:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://turbosms.in.ua/api/Turbo", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebMethod(operationName = "SendSMS", action = "http://turbosms.in.ua/api/Turbo/SendSMS")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.SendSMSResponse")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    public ArrayOfString sendSMS(
            @WebParam(name = "sender", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String sender,
            @WebParam(name = "destination", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String destination,
            @WebParam(name = "text", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String text,
            @WebParam(name = "wappush", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String wappush
    );

    @WebMethod(operationName = "GetCreditBalance", action = "http://turbosms.in.ua/api/Turbo/GetCreditBalance")
    @RequestWrapper(localName = "GetCreditBalance", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.GetCreditBalance")
    @ResponseWrapper(localName = "GetCreditBalanceResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.GetCreditBalanceResponse")
    @WebResult(name = "GetCreditBalanceResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    public String getCreditBalance();

    @WebMethod(operationName = "GetNewMessages", action = "http://turbosms.in.ua/api/Turbo/GetNewMessages")
    @RequestWrapper(localName = "GetNewMessages", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.GetNewMessages")
    @ResponseWrapper(localName = "GetNewMessagesResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.GetNewMessagesResponse")
    @WebResult(name = "GetNewMessagesResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    public ArrayOfString getNewMessages();

    @WebMethod(operationName = "Auth", action = "http://turbosms.in.ua/api/Turbo/Auth")
    @RequestWrapper(localName = "Auth", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.Auth")
    @ResponseWrapper(localName = "AuthResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.AuthResponse")
    @WebResult(name = "AuthResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    public String auth(
            @WebParam(name = "login", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String login,
            @WebParam(name = "password", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String password
    );

    @WebMethod(operationName = "GetMessageStatus", action = "http://turbosms.in.ua/api/Turbo/GetMessageStatus")
    @RequestWrapper(localName = "GetMessageStatus", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.GetMessageStatus")
    @ResponseWrapper(localName = "GetMessageStatusResponse", targetNamespace = "http://turbosms.in.ua/api/Turbo", className = "ua.turbosms.GetMessageStatusResponse")
    @WebResult(name = "GetMessageStatusResult", targetNamespace = "http://turbosms.in.ua/api/Turbo")
    public String getMessageStatus(
            @WebParam(name = "MessageId", targetNamespace = "http://turbosms.in.ua/api/Turbo")
                    String messageId
    );
}
